services:
    admin_security:
        class: AdminBundle\EventListener\SecurityListener
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: [ @router, @service_container, %encryption_key%]

#        kernel.event_listener 注册事件监听器
#        kernel.event_subscriber 注册订阅