# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        AppBundle\Entity\Tuser:
            algorithm: bcrypt

    providers:
        in_memory:
            memory: ~
#        db_provider:
#            entity:
#                class: AppBundle:Tuser
    firewalls:
        main:
            anonymous: ~
#            provider: db_provider

    acl:
        connection: default

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }