<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdPositionRepository extends EntityRepository
{
}
