<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAreaRepository extends EntityRepository
{
}
