<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivityFilmTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivityFilmTicketRepository extends EntityRepository
{
}
