<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivityFilmRaffleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivityFilmRaffleRepository extends EntityRepository
{
}
