<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivityVshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivityVshowRepository extends EntityRepository
{
}
