<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdvShenheLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdvShenheLogRepository extends EntityRepository
{
}
