<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAreaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAreaDataRepository extends EntityRepository
{
}
