<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdminsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdminsRepository extends EntityRepository
{
}
