<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdvPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdvPlaceRepository extends EntityRepository
{
}
