<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAttachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAttachRepository extends EntityRepository
{
}
