<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAnswerToUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAnswerToUserRepository extends EntityRepository
{
}
