<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdviceRepository extends EntityRepository
{
}
