<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjAdvShenheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjAdvShenheRepository extends EntityRepository
{
}
