<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjApacheLogStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjApacheLogStatusRepository extends EntityRepository
{
}
