<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivitieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivitieRepository extends EntityRepository
{
}
