<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivityFilmUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivityFilmUsersRepository extends EntityRepository
{
}
