<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivityHeadlineWechatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivityHeadlineWechatRepository extends EntityRepository
{
}
