<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjActivitieSpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjActivitieSpecialRepository extends EntityRepository
{
}
