<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjBusinessPlanKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjBusinessPlanKeywordRepository extends EntityRepository
{
}
