<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjBlueBookZhengdingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjBlueBookZhengdingRepository extends EntityRepository
{
}
