<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjCwnUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjCwnUsersRepository extends EntityRepository
{
}
