<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjCartRepository extends EntityRepository
{
}
