<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjConfigProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjConfigProductRepository extends EntityRepository
{
}
