<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjCreditConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjCreditConfigRepository extends EntityRepository
{
}
