<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjClickLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjClickLogRepository extends EntityRepository
{
}
