<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjCreditCateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjCreditCateRepository extends EntityRepository
{
}
