<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjEduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjEduRepository extends EntityRepository
{
}
