<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFormAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFormAttrRepository extends EntityRepository
{
}
