<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFormFieldCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFormFieldCategoryRepository extends EntityRepository
{
}
