<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFundsInstitutionManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFundsInstitutionManagerRepository extends EntityRepository
{
}
