<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFormFieldValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFormFieldValueRepository extends EntityRepository
{
}
