<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFormCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFormCategoryRepository extends EntityRepository
{
}
