<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFormAttrTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFormAttrTypeRepository extends EntityRepository
{
}
