<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjFundsInstitutionRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjFundsInstitutionRecordRepository extends EntityRepository
{
}
