<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjGoodZjxmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjGoodZjxmRepository extends EntityRepository
{
}
