<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjGuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjGuestRepository extends EntityRepository
{
}
