<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjHomepageItemCateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjHomepageItemCateRepository extends EntityRepository
{
}
