<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjInfoCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjInfoCommentRepository extends EntityRepository
{
}
