<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjInnerWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjInnerWordsRepository extends EntityRepository
{
}
