<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjInnerWordsRelevanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjInnerWordsRelevanceRepository extends EntityRepository
{
}
