<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjInvestorsColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjInvestorsColumnRepository extends EntityRepository
{
}
