<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjIndustryOldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjIndustryOldRepository extends EntityRepository
{
}
