<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjItemFeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjItemFeedbackRepository extends EntityRepository
{
}
