<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjIndustryNewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjIndustryNewRepository extends EntityRepository
{
}
