<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjJobRepository extends EntityRepository
{
}
