<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjLoginLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjLoginLogRepository extends EntityRepository
{
}
