<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjMessageIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjMessageIndexRepository extends EntityRepository
{
}
