<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjMessageContentJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjMessageContentJoinRepository extends EntityRepository
{
}
