<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjMessageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjMessageContentRepository extends EntityRepository
{
}
