<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjMobileBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjMobileBlacklistRepository extends EntityRepository
{
}
