<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjNewsClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjNewsClickRepository extends EntityRepository
{
}
