<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjNewsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjNewsContentRepository extends EntityRepository
{
}
