<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjNewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjNewsCategoryRepository extends EntityRepository
{
}
