<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjNewsViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjNewsViewRepository extends EntityRepository
{
}
