<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjNewsRepository extends EntityRepository
{
}
