<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjOrderDeliveryPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjOrderDeliveryPackageRepository extends EntityRepository
{
}
