<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjOrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjOrgRepository extends EntityRepository
{
}
