<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjOrgDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjOrgDetailRepository extends EntityRepository
{
}
