<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjPriceRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjPriceRuleRepository extends EntityRepository
{
}
