<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjPublicTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjPublicTopicRepository extends EntityRepository
{
}
