<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjRczgTopicContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjRczgTopicContentRepository extends EntityRepository
{
}
