<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjReportRepository extends EntityRepository
{
}
