<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjRemindEmailLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjRemindEmailLogRepository extends EntityRepository
{
}
