<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjRolesRepository extends EntityRepository
{
}
