<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjRczgTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjRczgTopicRepository extends EntityRepository
{
}
