<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSalonTopicDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSalonTopicDataRepository extends EntityRepository
{
}
