<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSiteBroadcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSiteBroadcastRepository extends EntityRepository
{
}
