<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSeoManageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSeoManageRepository extends EntityRepository
{
}
