<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSpecialSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSpecialSubjectRepository extends EntityRepository
{
}
