<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSalonTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSalonTopicRepository extends EntityRepository
{
}
