<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSalesReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSalesReportRepository extends EntityRepository
{
}
