<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSmsCodeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSmsCodeLogRepository extends EntityRepository
{
}
