<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSuccessCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSuccessCaseRepository extends EntityRepository
{
}
