<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSeoManageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSeoManageCategoryRepository extends EntityRepository
{
}
