<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSiteRepository extends EntityRepository
{
}
