<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSemPlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSemPlayRepository extends EntityRepository
{
}
