<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjSettingRepository extends EntityRepository
{
}
