<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTravelRaffleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTravelRaffleRepository extends EntityRepository
{
}
