<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTravelXmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTravelXmRepository extends EntityRepository
{
}
