<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjThinktankStarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjThinktankStarRepository extends EntityRepository
{
}
