<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjThinktankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjThinktankRepository extends EntityRepository
{
}
