<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTagRepository extends EntityRepository
{
}
