<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTopicRepository extends EntityRepository
{
}
