<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTmpImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTmpImportRepository extends EntityRepository
{
}
