<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTravelRaffleResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTravelRaffleResultRepository extends EntityRepository
{
}
