<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTrustRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTrustRepository extends EntityRepository
{
}
