<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTrustContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTrustContentRepository extends EntityRepository
{
}
