<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTopicColumnContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTopicColumnContentRepository extends EntityRepository
{
}
