<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTgxxZjxmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTgxxZjxmRepository extends EntityRepository
{
}
