<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTagRelevanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTagRelevanceRepository extends EntityRepository
{
}
