<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTmpNewSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTmpNewSiteRepository extends EntityRepository
{
}
