<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTgxxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTgxxRepository extends EntityRepository
{
}
