<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTopicTenkanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTopicTenkanRepository extends EntityRepository
{
}
