<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjTongjiHostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjTongjiHostRepository extends EntityRepository
{
}
