<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersMessageIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersMessageIndexRepository extends EntityRepository
{
}
