<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersPublishTjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersPublishTjRepository extends EntityRepository
{
}
