<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersFollowRepository extends EntityRepository
{
}
