<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersRssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersRssRepository extends EntityRepository
{
}
