<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersNoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersNoticeRepository extends EntityRepository
{
}
