<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjVoteResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjVoteResultRepository extends EntityRepository
{
}
