<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjWebcastRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjWebcastRecordRepository extends EntityRepository
{
}
