<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjWebcastCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjWebcastCommentRepository extends EntityRepository
{
}
