<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjWordsRepository extends EntityRepository
{
}
