<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjWebcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjWebcastRepository extends EntityRepository
{
}
