<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjWebKeywordInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjWebKeywordInfoRepository extends EntityRepository
{
}
