<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZtLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZtLogRepository extends EntityRepository
{
}
