<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZjxmViewLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZjxmViewLogsRepository extends EntityRepository
{
}
