<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZjxmListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZjxmListRepository extends EntityRepository
{
}
