<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZjxmContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZjxmContactRepository extends EntityRepository
{
}
