<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZjxmQuickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZjxmQuickRepository extends EntityRepository
{
}
