<?php

namespace SharedModel;

use Doctrine\ORM\EntityRepository;

/**
 * TrjZjxmSmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjZjxmSmsRepository extends EntityRepository
{
}
