SharedModel\TrjActivityHeadlineWechat:
    type: entity
    repositoryClass: SharedModel\TrjActivityHeadlineWechatRepository
    table: trj_activity_headline_wechat
    uniqueConstraints:
        ak_user_id_trj_activity_headline_wechat:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 用户id
            default: '0'
            column: user_id
        addTime:
            type: integer
            nullable: false
            unsigned: false
            comment: '参加时间'
            default: '0'
            column: add_time
        itemText:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 项目创意或创业理想
            column: item_text
    lifecycleCallbacks: {  }
