SharedModel\TrjAdmins:
    type: entity
    repositoryClass: SharedModel\TrjAdminsRepository
    table: trj_admins
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        password:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: ''
        lastlogin:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        bdate:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        truename:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        roleid:
            type: smallint
            nullable: false
            unsigned: false
            comment: 所属角色
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: '使用状态1:使用 2:停用'
            default: '1::smallint'
    lifecycleCallbacks: {  }
