SharedModel\TrjActionsRole:
    type: entity
    repositoryClass: SharedModel\TrjActionsRoleRepository
    table: trj_actions_role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        roleid:
            type: integer
            nullable: true
            unsigned: false
            comment: '映射角色表'
        actionid:
            type: integer
            nullable: true
            unsigned: false
            comment: '映射权限表'
        masterid:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        mastername:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        createdate:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
