SharedModel\TrjActivitieBm:
    type: entity
    repositoryClass: SharedModel\Repository\TrjActivitieBmRepository
    table: trj_activitie_bm
    uniqueConstraints:
        ak_aid_trj_activitie_bm:
            columns:
                - aid
        trj_activitie_bm_pk:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        aid:
            type: integer
            nullable: false
            unsigned: false
            comment: 活动id
            default: '0'
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 名字
        username:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 用户名
        mobile:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: 手机
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: 报名时间
            default: '0'
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: '审核状态1通过2未通过'
            default: '0::smallint'
        isDel:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0::smallint'
            column: is_del
    lifecycleCallbacks: {  }
