SharedModel\TrjApacheLogStatus:
    type: entity
    repositoryClass: SharedModel\Repository\TrjApacheLogStatusRepository
    table: trj_apache_log_status
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        theDate:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: the_date
        startTime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: start_time
        endTime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: end_time
    lifecycleCallbacks: {  }
