SharedModel\TrjCustomerTopic:
    type: entity
    repositoryClass: SharedModel\Repository\TrjCustomerTopicRepository
    table: trj_customer_topic
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: '标题'
        topBanner:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: banner
            column: top_banner
        topBannerHeight:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: top_banner_height
        att:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 附件
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: 创建时间
            default: '0'
        createId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: create_id
        createName:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: create_name
        updated:
            type: integer
            nullable: false
            unsigned: false
            comment: 生成时间
            default: '0'
        sendtime:
            type: integer
            nullable: false
            unsigned: false
            comment: 发送时间
            default: '0'
        sendnum:
            type: integer
            nullable: false
            unsigned: false
            comment: 发送次数
            default: '0'
        isInit:
            type: smallint
            nullable: false
            unsigned: false
            comment: 是否初始化
            default: '0::smallint'
            column: is_init
        isQueue:
            type: smallint
            nullable: false
            unsigned: false
            comment: '是否已加入队列'
            default: '0::smallint'
            column: is_queue
        state:
            type: smallint
            nullable: false
            unsigned: false
            comment: '状态 0:未发送 1:已发送'
            default: '0::smallint'
        createUrl:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 生成的url
            column: create_url
        template:
            type: integer
            nullable: false
            unsigned: false
            comment: 模版
            default: '0'
        sendConfig:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 发送规则
            column: send_config
    lifecycleCallbacks: {  }
