SharedModel\TrjHomepageGuest:
    type: entity
    repositoryClass: SharedModel\Repository\TrjHomepageGuestRepository
    table: trj_homepage_guest
    uniqueConstraints:
        ak_user_id_trj_homepage_guest:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 被评论对象
            default: '0'
            column: user_id
        content:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 留言
            default: ''
        replyContent:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 回复
            default: ''
            column: reply_content
        replyTime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: reply_time
        posterId:
            type: integer
            nullable: false
            unsigned: false
            comment: '评论者'
            default: '0'
            column: poster_id
        poster:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: '评论者'
            default: ''
        flag:
            type: smallint
            nullable: false
            unsigned: false
            comment: 是否已查看
            default: '0::smallint'
        showType:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0::smallint'
            column: show_type
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
