SharedModel\TrjHomepageNewsComment:
    type: entity
    repositoryClass: SharedModel\Repository\TrjHomepageNewsCommentRepository
    table: trj_homepage_news_comment
    uniqueConstraints:
        ak_news_id_trj_homepage_news_comment:
            columns:
                - news_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        newsId:
            type: integer
            nullable: false
            unsigned: false
            comment: 被评论对象
            default: '0'
            column: news_id
        content:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 留言
        posterId:
            type: integer
            nullable: false
            unsigned: false
            comment: '评论者'
            default: '0'
            column: poster_id
        poster:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: '评论者'
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
