SharedModel\TrjHomepageLink:
    type: entity
    repositoryClass: SharedModel\Repository\TrjHomepageLinkRepository
    table: trj_homepage_link
    uniqueConstraints:
        ak_user_id_trj_homepage_link:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        siteUrl:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: site_url
        siteName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: site_name
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 所属人
            default: '0'
            column: user_id
        sort:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
