SharedModel\TrjInnerWordsRelevance:
    type: entity
    repositoryClass: SharedModel\TrjInnerWordsRelevanceRepository
    table: trj_inner_words_relevance
    uniqueConstraints:
        ak_iid_trj_inner_words_relevance:
            columns:
                - iid
        ak_info_id_trj_inner_words_relevance:
            columns:
                - info_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        iid:
            type: integer
            nullable: false
            unsigned: false
            comment: '关键字id'
            default: '0'
        type:
            type: smallint
            nullable: false
            unsigned: false
            comment: 类型：1资金项目2资讯
            default: '0::smallint'
        infoId:
            type: integer
            nullable: false
            unsigned: false
            comment: 信息id
            default: '0'
            column: info_id
    lifecycleCallbacks: {  }
