SharedModel\TrjIndustry:
    type: entity
    repositoryClass: SharedModel\TrjIndustryRepository
    table: trj_industry
    uniqueConstraints:
        trj_industry_pk:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        parentId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: parent_id
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        seoTitle:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            column: seo_title
        seoKeywords:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            column: seo_keywords
        seoDescription:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            column: seo_description
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '1::smallint'
        sort:
            type: smallint
            nullable: false
            unsigned: false
            comment: 排序
            default: '0'
    lifecycleCallbacks: {  }
