SharedModel\TrjNewsView:
    type: entity
    repositoryClass: SharedModel\Repository\TrjNewsViewRepository
    table: trj_news_view
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        type:
            type: smallint
            nullable: false
            unsigned: false
            comment: 1资讯2智库
            default: '0::smallint'
        newsId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: news_id
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: user_id
        updated:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
