SharedModel\TrjSeoRank:
    type: entity
    repositoryClass: SharedModel\TrjSeoRankRepository
    table: trj_seo_rank
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 主键
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        rankBd:
            type: integer
            nullable: false
            unsigned: false
            comment: 百度排名，0表示没有排名
            default: '0'
            column: rank_bd
        rank360:
            type: integer
            nullable: false
            unsigned: false
            comment: 360排名，0表示没有排名
            default: '0'
            column: rank_360
        keyword:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: '关键词'
        link:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 链接地址
        attr:
            type: smallint
            nullable: false
            unsigned: false
            comment: '1商业词 2高流量 3长尾词'
            default: '1::smallint'
        index:
            type: integer
            nullable: false
            unsigned: false
            comment: 指数
        creator:
            type: integer
            nullable: false
            unsigned: false
            comment: 维护人员
        trendBd:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 百度排名趋势
            column: trend_bd
        trend360:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 360排名趋势
            column: trend_360
    lifecycleCallbacks: {  }
