SharedModel\TrjSuccessfulCase:
    type: entity
    repositoryClass: SharedModel\Repository\TrjSuccessfulCaseRepository
    table: trj_successful_case
    uniqueConstraints:
        trj_successful_case_pk:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: '审核状态'
            default: '0::smallint'
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        updated:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 活动介绍
        file:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
        poster:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: 提交人
            default: ''
    lifecycleCallbacks: {  }
