SharedModel\TrjSmsCodeLog:
    type: entity
    repositoryClass: SharedModel\TrjSmsCodeLogRepository
    table: trj_sms_code_log
    uniqueConstraints:
        ak_is_reg_trj_sms_code_log:
            columns:
                - is_reg
        ak_mobile_trj_sms_code_log:
            columns:
                - mobile
        ak_created_trj_sms_code_log:
            columns:
                - created
                - is_distribution
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        siteId:
            type: integer
            nullable: false
            unsigned: false
            comment: 分站ID
            default: '0'
            column: site_id
        type:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        way:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        mobile:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
        isReg:
            type: smallint
            nullable: false
            unsigned: false
            comment: '手机号码是号已注册'
            default: '0::smallint'
            column: is_reg
        isProcess:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0::smallint'
            column: is_process
        isVoice:
            type: smallint
            nullable: false
            unsigned: false
            comment: 是否发送语音
            default: '0::smallint'
            column: is_voice
        isDistribution:
            type: smallint
            nullable: false
            unsigned: false
            comment: 是否已导
            default: '0::smallint'
            column: is_distribution
        fromWeb:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0::smallint'
            column: from_web
        processRemark:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            default: ''
            column: process_remark
        code:
            type: string
            nullable: false
            length: 6
            fixed: true
            comment: ''
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        minfoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: minfo_id
        trackid:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        referer:
            type: string
            nullable: true
            length: 2000
            fixed: false
            comment: 站外来源
        seoCat:
            type: smallint
            nullable: false
            unsigned: false
            comment: '1:为品牌SEO'
            default: '0::smallint'
            column: seo_cat
    lifecycleCallbacks: {  }
