SharedModel\TrjSemPlay:
    type: entity
    repositoryClass: SharedModel\TrjSemPlayRepository
    table: trj_sem_play
    uniqueConstraints:
        ak_isdel_trj_sem_play:
            columns:
                - isdel
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        pId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: p_id
        popularizePlatform:
            type: smallint
            nullable: true
            unsigned: false
            comment: ''
            column: popularize_platform
        popularizeAccount:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: popularize_account
        popularizePlan:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: popularize_plan
        popularizeUnit:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: popularize_unit
        posterId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: poster_id
        posterName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: poster_name
        addtime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        isdel:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
