SharedModel\TrjTgxx:
    type: entity
    repositoryClass: SharedModel\Repository\TrjTgxxRepository
    table: trj_tgxx
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        qi:
            type: integer
            nullable: false
            unsigned: false
            comment: 期号
            default: '0'
        subject:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: '标题'
        templete:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        content1:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content_1
        content2:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content_2
        content3:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content_3
        content4:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content_4
        content5:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content_5
        sendDatetime:
            type: integer
            nullable: false
            unsigned: false
            comment: 发送时间
            default: '0'
            column: send_datetime
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '1::smallint'
        createName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: '录入人'
            column: create_name
        createId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: create_id
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        isInit:
            type: smallint
            nullable: false
            unsigned: false
            comment: 发送人是否已初始化
            default: '0::smallint'
            column: is_init
        flag:
            type: smallint
            nullable: false
            unsigned: false
            comment: '1：可以正式发送,2:已发送'
            default: '0::smallint'
        isResult:
            type: smallint
            nullable: false
            unsigned: false
            comment: 是否已产生结果
            default: '0::smallint'
            column: is_result
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
