SharedModel\TrjTestUsers:
    type: entity
    repositoryClass: SharedModel\TrjTestUsersRepository
    table: trj_test_users
    uniqueConstraints:
        ak_username_trj_test_users:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: 用户账号
        num:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
