SharedModel\TrjTag:
    type: entity
    repositoryClass: SharedModel\TrjTagRepository
    table: trj_tag
    uniqueConstraints:
        ak_tag_name_trj_tag:
            columns:
                - tag_name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        tagName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: tag_name
        type:
            type: smallint
            nullable: false
            unsigned: false
            comment: '1 项目 2资金 3文章4问答,6成功案例'
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: '0 启用 1 停用'
            default: '0::smallint'
        itemNumber:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: item_number
        fundsNumber:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: funds_number
        articleNumber:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: article_number
        sumNumber:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: sum_number
        times:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        isdel:
            type: smallint
            nullable: false
            unsigned: false
            comment: '是否删除0:正常 1:删除'
            default: '0::smallint'
    lifecycleCallbacks: {  }
