SharedModel\TrjTuiding:
    type: entity
    repositoryClass: SharedModel\Repository\TrjTuidingRepository
    table: trj_tuiding
    uniqueConstraints:
        trj_tuiding_pk:
            columns:
                - id
        ak_email_trj_tuiding:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        email:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
