SharedModel\TrjUsersWapBusinesscard:
    type: entity
    repositoryClass: SharedModel\TrjUsersWapBusinesscardRepository
    table: trj_users_wap_businesscard
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: user_id
        zjxmId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: zjxm_id
    lifecycleCallbacks: {  }
