SharedModel\TrjUsersBank:
    type: entity
    repositoryClass: SharedModel\Repository\TrjUsersBankRepository
    table: trj_users_bank
    uniqueConstraints:
        ak_user_id_trj_users_bank:
            columns:
                - user_id
        trj_users_bank_pk:
            columns:
                - id
        ak_order_sn_trj_users_bank:
            columns:
                - order_sn
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 用户ID
            default: '0'
            column: user_id
        idName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 姓名
            column: id_name
        idNo:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 身份证号
            column: id_no
        bankAccount:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 银行帐号
            column: bank_account
        bankCode:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 连连银行代号
            column: bank_code
        bankMobile:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: '手机号码'
            column: bank_mobile
        orderSn:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: order_sn
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0::smallint'
    lifecycleCallbacks: {  }
