SharedModel\TrjUsersFeed:
    type: entity
    repositoryClass: SharedModel\Repository\TrjUsersFeedRepository
    table: trj_users_feed
    uniqueConstraints:
        ak_user_id_trj_users_feed:
            columns:
                - user_id
        ak_feed_md5_trj_users_feed:
            columns:
                - feed_md5
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        siteId:
            type: integer
            nullable: false
            unsigned: false
            comment: 分站ID
            default: '0'
            column: site_id
        icon:
            type: smallint
            nullable: false
            unsigned: false
            comment: 详见get_feed_icon函数
            default: '0::smallint'
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: user_id
        bodyData:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: body_data
        feedMd5:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
            column: feed_md5
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '1::smallint'
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        flag:
            type: smallint
            nullable: false
            unsigned: false
            comment: 1表示是发起人
            default: '0::smallint'
    lifecycleCallbacks: {  }
