SharedModel\TrjWords:
    type: entity
    repositoryClass: SharedModel\Repository\TrjWordsRepository
    table: trj_words
    uniqueConstraints:
        trj_words_pk:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        createId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: create_id
        created:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
