AppBundle\Entity\AclClasses:
    type: entity
    repositoryClass: AppBundle\Entity\AclClassesRepository
    table: acl_classes
    uniqueConstraints:
        uniq_69dd750638a36066:
            columns:
                - class_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        classType:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: class_type
    lifecycleCallbacks: {  }
