AppBundle\Entity\AclEntries:
    type: entity
    repositoryClass: AppBundle\Entity\AclEntriesRepository
    table: acl_entries
    indexes:
        idx_46c8b806ea000b103d9ab4a6df9183c9:
            columns:
                - class_id
                - object_identity_id
                - security_identity_id
        idx_46c8b806ea000b10:
            columns:
                - class_id
        idx_46c8b8063d9ab4a6:
            columns:
                - object_identity_id
        idx_46c8b806df9183c9:
            columns:
                - security_identity_id
    uniqueConstraints:
        uniq_46c8b806ea000b103d9ab4a64def17bce4289bf4:
            columns:
                - class_id
                - object_identity_id
                - field_name
                - ace_order
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fieldName:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: field_name
        aceOrder:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            column: ace_order
        mask:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        granting:
            type: boolean
            nullable: false
            comment: ''
        grantingStrategy:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: granting_strategy
        auditSuccess:
            type: boolean
            nullable: false
            comment: ''
            column: audit_success
        auditFailure:
            type: boolean
            nullable: false
            comment: ''
            column: audit_failure
    manyToOne:
        class:
            targetEntity: AclClasses
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                class_id:
                    referencedColumnName: id
            orphanRemoval: false
        objectentity:
            targetEntity: AclObjectIdentities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                object_identity_id:
                    referencedColumnName: id
            orphanRemoval: false
        securityentity:
            targetEntity: AclSecurityIdentities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                security_identity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
