<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjCyDictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjCyDictRepository extends EntityRepository
{

    public function getCyName()
    {
        /*
         * 考虑到图片大小只有200*200,所以最多可以渲染七个汉字，一个utf-8汉字三字节，所以这里填写21.
         */
        return $this->getEntityManager()
            ->createQuery("select u.id,u.chengyu from Model:TrjCyDict u where LENGTH(u.chengyu)<=:chengyu")
            ->setParameter('chengyu',21)
            ->getResult();
    }

}
