<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjHelpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjHelpRepository extends EntityRepository
{
}
