<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjOrgSettleCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjOrgSettleCaseRepository extends EntityRepository
{
}
