<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjStatDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjStatDayRepository extends EntityRepository
{
}
