<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersCapitalCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersCapitalCaseRepository extends EntityRepository
{
}
