<?php

namespace SharedModel\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrjUsersWapBusinesscardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrjUsersWapBusinesscardRepository extends EntityRepository
{
}
